import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import { RiInstagramFill, RiWhatsappFill } from "react-icons/ri";
import { Product } from "@/components/Product";
import products from "@/lib/products";

export default function Home() {
  const [menu, setMenu] = useState(0);
  return (
    <>
      <Head>
        <title>Carpicenter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      {/* <Header /> */}
      <div className="w-full lg:h-full flex justify-center items-center bg-white">
        <div className="bg-white h-full w-full max-w-[60rem]">
          <div className="w-full sm:h-[18rem] h-[15rem] rounded-b-lg bg-gradient-to-t from-black/50 to-transparent flex items-end justify-end">
            <Image
              width={3000}
              height={3000}
              priority
              className="object-cover w-full h-full rounded-b-xl"
              src="https://images.pexels.com/photos/298842/pexels-photo-298842.jpeg"
              alt="Profile"
            />
          </div>
          <div className="w-full px-3 relative bg-white text-[#292929]">
            <div className="w-full flex-row lg:justify-between lg:flex">
              <div className="w-full flex flex-col lg:flex items-center gap-3 relative">
                <div className="bg-white rounded-xl p-4 absolute bottom-36 lg:bottom-9 lg:left-0 w-40 h-40 flex items-center justify-center cursor-pointer border-4 border-gray">
                  <Image
                    width={150}
                    height={150}
                    priority
                    className="object-cover"
                    src="/logo.svg"
                    alt="Profile"
                  />

                  <div className="absolute w-full h-full bg-gray/5 duration-100 hover:bg-gray/10"></div>
                </div>
                <div className="flex flex-col gap-2 py-6 ml-0 mt-16 items-center lg:items-start lg:mt-0">
                  <p className=" text-4xl font-bold">Carpicenter</p>
                  <p className=" font-medium text-lg w-full hover:underline cursor-pointer">
                    Clientes actuales 204
                  </p>
                </div>
              </div>
              <div className="w-full justify-center pb-5 lg:w-1/2 flex lg:items-end lg:justify-end gap-2 lg:py-5">
                <a
                  href="https://api.whatsapp.com/send?phone=+5493582445849&text=Quiero%20comprar%20un%20mueble"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="flex items-center gap-2 border border-green-500 bg-green-500 text-white py-2 px-3 rounded-md duration-150 cursor-pointer hover:bg-green-400"
                >
                  <RiWhatsappFill />
                  <h2 className="font-medium text-sm">WhatsApp</h2>
                </a>
                <div className="flex items-center gap-2 border   py-2 px-3 rounded-md duration-150 cursor-pointer hover:bg-gray">
                  <RiInstagramFill />
                  <h2 className="font-medium text-sm">Instagram</h2>
                </div>
              </div>
            </div>
            <div className="w-full h-[1px] bg-black/10"></div>
            <div className="pt-1 flex items-center justify-between">
              <ul className="text-black/60 font-medium text-lg flex gap-0">
                <li
                  onClick={() => setMenu(0)}
                  className="text-blue-500 border-b-2 border-blue-500 duration-150 cursor-pointer py-3 px-4"
                >
                  Productos
                </li>
                <li
                  onClick={() => setMenu(1)}
                  className="duration-150 cursor-pointer hover:bg-white/10 py-3 px-4 rounded-md mb-1"
                >
                  Información
                </li>

                <li
                  onClick={() => setMenu(2)}
                  className="duration-150 cursor-pointer hover:bg-white/10 py-3 px-4 rounded-md mb-1 hidden md:block"
                >
                  Fotos
                </li>
              </ul>
            </div>
            <div className="w-full h-[1px] bg-black/10"></div>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-3   gap-4 p-4">
            {menu === 0
              ? products.map((product) => (
                  <Product
                    key={product.id}
                    image={product.image}
                    title={product.title}
                    description={product.description}
                    price={product.price}
                    pay={product.pay}
                  />
                ))
              : null}
          </div>
        </div>
      </div>
    </>
  );
}
